const QUESTIONS = [
  { q: "Theo Hồ Chí Minh, đạo đức có vai trò gì đối với người cách mạng?", options: ["Là gốc, là nền tảng", "Là phương tiện", "Là mục tiêu cuối cùng", "Là hình thức"], correct: 0 },
  { q: "Phẩm chất đạo đức hàng đầu theo tư tưởng HCM là gì?", options: ["Cần kiệm liêm chính", "Trung với nước, hiếu với dân", "Chí công vô tư", "Yêu thương con người"], correct: 1 },
  { q: "'Cần' trong tư tưởng đạo đức HCM có nghĩa là gì?", options: ["Tiết kiệm", "Siêng năng, chăm chỉ", "Trong sạch", "Chính trực"], correct: 1 },
  { q: "'Kiệm' trong tư tưởng đạo đức HCM có nghĩa là gì?", options: ["Siêng năng", "Tiết kiệm, không xa xỉ", "Liêm khiết", "Trung thực"], correct: 1 },
  { q: "'Liêm' trong tư tưởng đạo đức HCM có nghĩa là gì?", options: ["Tiết kiệm", "Chăm chỉ", "Trong sạch, không tham lam", "Ngay thẳng"], correct: 2 },
  { q: "'Chính' trong tư tưởng đạo đức HCM có nghĩa là gì?", options: ["Không tham lam", "Không xa xỉ", "Chăm chỉ", "Ngay thẳng, không tà"], correct: 3 },
  { q: "Hồ Chí Minh ví đạo đức như gì của cây?", options: ["Lá", "Hoa", "Gốc/Rễ", "Cành"], correct: 2 },
  { q: "'Chí công vô tư' theo HCM nghĩa là gì?", options: ["Không quan tâm ai", "Đặt lợi ích chung lên trên lợi ích cá nhân", "Làm việc một mình", "Không nhận lương"], correct: 1 },
  { q: "Theo HCM, đối lập với 'chí công vô tư' là gì?", options: ["Yêu nước", "Đoàn kết", "Chủ nghĩa cá nhân", "Tự do"], correct: 2 },
  { q: "HCM coi chủ nghĩa cá nhân là gì?", options: ["Phẩm chất tốt", "Kẻ thù nguy hiểm nhất", "Điều bình thường", "Quyền con người"], correct: 1 },
  { q: "Nguyên tắc đạo đức nào HCM đề cao nhất trong thực hành?", options: ["Học nhiều lý thuyết", "Nói đi đôi với làm", "Nói hay hơn làm", "Làm không cần nói"], correct: 1 },
  { q: "Theo HCM, phương pháp rèn luyện đạo đức quan trọng là gì?", options: ["Đọc sách", "Tự phê bình và phê bình", "Đi du lịch", "Tập thể dục"], correct: 1 },
  { q: "HCM nói: 'Người cách mạng phải có ___'?", options: ["Tiền bạc", "Đạo đức cách mạng", "Quyền lực", "Danh vọng"], correct: 1 },
  { q: "'Trung với nước' theo HCM mang nội dung gì mới?", options: ["Trung với vua", "Trung thành với sự nghiệp dựng nước và giữ nước của nhân dân", "Trung thành với đồng minh", "Trung thành với bạn bè"], correct: 1 },
  { q: "'Hiếu với dân' theo HCM có nghĩa là gì?", options: ["Hiếu thảo với cha mẹ", "Phục vụ nhân dân hết lòng", "Nghe lời dân", "Cho dân tiền"], correct: 1 },
  { q: "Theo HCM, yêu thương con người phải gắn liền với gì?", options: ["Ghét bỏ kẻ xấu", "Đấu tranh chống áp bức, bất công", "Cho tiền người nghèo", "Nói lời hay"], correct: 1 },
  { q: "HCM quan niệm tinh thần quốc tế trong sáng là gì?", options: ["Bài ngoại", "Đoàn kết với nhân dân các nước vì hòa bình, công lý", "Sống cô lập", "Chỉ quan hệ nước lớn"], correct: 1 },
  { q: "Theo HCM, đạo đức cách mạng khác đạo đức cũ ở điểm nào?", options: ["Phục vụ vua chúa", "Phục vụ nhân dân, dân tộc", "Phục vụ cá nhân", "Phục vụ tôn giáo"], correct: 1 },
  { q: "HCM nhấn mạnh mối quan hệ giữa đức và tài như thế nào?", options: ["Chỉ cần tài", "Chỉ cần đức", "Có tài mà không có đức là vô dụng", "Đức và tài không liên quan"], correct: 2 },
  { q: "Tác phẩm nào của HCM bàn nhiều về đạo đức cách mạng?", options: ["Bản án chế độ thực dân", "Đường Kách Mệnh", "Sửa đổi lối làm việc", "Tuyên ngôn độc lập"], correct: 2 },
  { q: "HCM viết: 'Đạo đức cách mạng không phải ___'?", options: ["Từ trên trời sa xuống", "Do học mà có", "Do rèn luyện", "Tự nhiên có"], correct: 0 },
  { q: "Theo HCM, muốn xây dựng CNXH trước hết cần gì?", options: ["Nhiều tiền", "Con người XHCN (có đạo đức)", "Vũ khí", "Công nghệ"], correct: 1 },
  { q: "HCM đề cao đức tính nào trong sinh hoạt hàng ngày?", options: ["Xa hoa", "Giản dị", "Phô trương", "Lãng phí"], correct: 1 },
  { q: "Theo HCM, rèn luyện đạo đức phải thực hiện như thế nào?", options: ["Chỉ khi trẻ", "Thường xuyên, suốt đời", "Khi có thời gian rảnh", "Chỉ khi làm cán bộ"], correct: 1 },
  { q: "HCM nói: 'Một dân tộc, một đảng... mỗi ngày phải ___'?", options: ["Nghỉ ngơi", "Tự kiểm điểm, tự sửa chữa", "Đấu tranh", "Học tập nước ngoài"], correct: 1 },
];

export default QUESTIONS;
